version: '3.8'

services:
  edc-consumer-frontend:
    build:
      context: .
      args:
        - API_URL=http://172.16.56.42/consumer/cp/api/management
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://172.16.56.42/consumer/cp/api/management
    networks:
      - edc-network
      - kind  # Add the container to the 'kind' network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  edc-network:
    driver: bridge
  kind:
    external: true  # Use the existing 'kind' network

