version: '3.8'

services:
  edc-consumer-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://172.16.56.42/consumer/cp/api/management
      - WATCHPACK_POLLING=true  # Enable file watching in Docker
      - PORT=3001
    volumes:
      - ./:/app  # Mount the current directory to /app in the container
      - /app/node_modules  # Don't override node_modules with host's
    networks:
      - edc-network
      - kind  # Add the container to the 'kind' network
    stdin_open: true  # Keep STDIN open for React DevTools
    tty: true  # Allocate a pseudo-TTY

networks:
  edc-network:
    driver: bridge
  kind:
    external: true  # Use the existing 'kind' network

