apiVersion: v1
kind: Service
metadata:
  name: poc-next-backend
  namespace: poc-next
  labels:
    app: poc-next-backend
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: poc-next-backend
---
apiVersion: v1
kind: Service
metadata:
  name: poc-next-frontend
  namespace: poc-next
  labels:
    app: poc-next-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: poc-next-frontend
